"""Generate a Markdown audit of hardcoded non-ASCII strings in app/*.py."""
from __future__ import annotations

import argparse
import collections
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
NON_ASCII_RE = re.compile(r"[^\x00-\x7f]+")


def classify(line: str) -> str:
    low = line.lower()
    if any(token in low for token in ("qmessagebox", "show_warning", "show_info", "raise ", "error", "exception")):
        return "error/message"
    if any(token in low for token in ("settooltip", "statustip", "tooltip", "showmessage")):
        return "tooltip/status"
    if any(
        token in low
        for token in (
            "qaction",
            "addaction",
            "qpushbutton",
            "qlabel",
            "settext",
            "addmenu",
            "placeholder",
            "setwindowtitle",
        )
    ):
        return "ui-label"
    if "_t(" in line or "get_translation" in line:
        return "i18n-ready"
    return "other"


def iter_matches(root: Path):
    for path in sorted((root / "app").rglob("*.py")):
        rel = path.relative_to(root)
        for lineno, line in enumerate(path.read_text(encoding="utf-8", errors="ignore").splitlines(), 1):
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            if NON_ASCII_RE.search(stripped):
                yield rel, lineno, classify(stripped), stripped


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=ROOT / "docs" / "HARDCODED_STRINGS.md")
    args = parser.parse_args(argv)

    rows = list(iter_matches(ROOT))
    by_category = collections.Counter(category for _path, _line, category, _text in rows)
    by_file = collections.Counter(str(path) for path, _line, _category, _text in rows)

    lines = [
        "# Hardcoded Strings Audit",
        "",
        "Generated by `scripts/audit_hardcoded_strings.py`.",
        "",
        "## Summary",
        "",
        f"- Total non-ASCII hardcoded string/code lines: {len(rows)}",
        f"- Files with matches: {len(by_file)}",
        "",
        "| Category | Count | Recommendation |",
        "|---|---:|---|",
    ]
    recommendations = {
        "ui-label": "Move high-traffic UI labels to language_manager keys.",
        "error/message": "Move user-facing errors and warnings to i18n keys first.",
        "tooltip/status": "Keep short status strings in i18n where reused; one-off diagnostics can remain.",
        "i18n-ready": "Already wrapped or near an i18n call; verify key coverage.",
        "other": "Review manually; many are comments, docs, JS snippets, or internal labels.",
    }
    for category, count in by_category.most_common():
        lines.append(f"| {category} | {count} | {recommendations.get(category, 'Review manually.')} |")

    lines.extend(["", "## Top Files", "", "| Count | File |", "|---:|---|"])
    for path, count in by_file.most_common(40):
        lines.append(f"| {count} | `{path}` |")

    lines.extend(
        [
            "",
            "## I18n Priority",
            "",
            "1. Dialog titles, warning/error text, and confirmation text.",
            "2. Main toolbar/menu labels and tooltips.",
            "3. AI/OCR/signing workflow labels.",
            "4. Status-bar messages that users see repeatedly.",
            "",
            "## Full Catalog",
            "",
            "| File | Line | Category | Text |",
            "|---|---:|---|---|",
        ]
    )
    for path, lineno, category, text in rows:
        escaped = text.replace("|", "\\|")
        lines.append(f"| `{path}` | {lineno} | {category} | `{escaped}` |")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {args.output} with {len(rows)} entries")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
